//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Data.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPIInfo7Entities : DbContext
    {
        public EPIInfo7Entities()
            : base("name=EPIInfo7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<metaBackground> metaBackgrounds { get; set; }
        public virtual DbSet<metaDataType> metaDataTypes { get; set; }
        public virtual DbSet<metaField> metaFields { get; set; }
        public virtual DbSet<metaFieldType> metaFieldTypes { get; set; }
        public virtual DbSet<metaGridColumn> metaGridColumns { get; set; }
        public virtual DbSet<metaImage> metaImages { get; set; }
        public virtual DbSet<metaLayerRenderType> metaLayerRenderTypes { get; set; }
        public virtual DbSet<metaLayer> metaLayers { get; set; }
        public virtual DbSet<metaLink> metaLinks { get; set; }
        public virtual DbSet<metaMapLayer> metaMapLayers { get; set; }
        public virtual DbSet<metaMapPoint> metaMapPoints { get; set; }
        public virtual DbSet<metaMap> metaMaps { get; set; }
        public virtual DbSet<metaPage> metaPages { get; set; }
        public virtual DbSet<metaPattern> metaPatterns { get; set; }
        public virtual DbSet<metaProgram> metaPrograms { get; set; }
        public virtual DbSet<metaView> metaViews { get; set; }
        public virtual DbSet<metaDbInfo> metaDbInfoes { get; set; }
        public virtual DbSet<Canva> Canvas { get; set; }
        public virtual DbSet<DataAccessRule> DataAccessRules { get; set; }
        public virtual DbSet<Datasource> Datasources { get; set; }
        public virtual DbSet<EIDatasource> EIDatasources { get; set; }
        public virtual DbSet<lk_RecordSource> lk_RecordSource { get; set; }
        public virtual DbSet<lk_Status> lk_Status { get; set; }
        public virtual DbSet<lk_SurveyType> lk_SurveyType { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<ResponseDisplaySetting> ResponseDisplaySettings { get; set; }
        public virtual DbSet<ResponseXml> ResponseXmls { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SharedCanvas> SharedCanvases { get; set; }
        public virtual DbSet<SurveyMetaData> SurveyMetaDatas { get; set; }
        public virtual DbSet<SurveyMetaDataView> SurveyMetaDataViews { get; set; }
        public virtual DbSet<SurveyResponse> SurveyResponses { get; set; }
        public virtual DbSet<SurveyResponseTracking> SurveyResponseTrackings { get; set; }
        public virtual DbSet<SurveyResponseUser> SurveyResponseUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserOrganization> UserOrganizations { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<familyset> familysets { get; set; }
        public virtual DbSet<SurveyMetaDataTransform> SurveyMetaDataTransforms { get; set; }
    }
}
