//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class metaField
    {
        public int FieldId { get; set; }
        public Nullable<System.Guid> UniqueId { get; set; }
        public string Name { get; set; }
        public string PromptText { get; set; }
        public string ControlFontFamily { get; set; }
        public string ControlFontStyle { get; set; }
        public Nullable<decimal> ControlFontSize { get; set; }
        public Nullable<double> ControlTopPositionPercentage { get; set; }
        public Nullable<double> ControlLeftPositionPercentage { get; set; }
        public Nullable<double> ControlHeightPercentage { get; set; }
        public Nullable<double> ControlWidthPercentage { get; set; }
        public Nullable<decimal> TabIndex { get; set; }
        public Nullable<bool> HasTabStop { get; set; }
        public string PromptFontFamily { get; set; }
        public string PromptFontStyle { get; set; }
        public Nullable<decimal> PromptFontSize { get; set; }
        public string PromptScriptName { get; set; }
        public Nullable<double> PromptTopPositionPercentage { get; set; }
        public Nullable<double> PromptLeftPositionPercentage { get; set; }
        public string ControlScriptName { get; set; }
        public Nullable<bool> ShouldRepeatLast { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<bool> IsReadOnly { get; set; }
        public Nullable<bool> ShouldRetainImageSize { get; set; }
        public Nullable<short> MaxLength { get; set; }
        public string Lower { get; set; }
        public string Upper { get; set; }
        public string Pattern { get; set; }
        public Nullable<bool> ShowTextOnRight { get; set; }
        public string CheckCodeBefore { get; set; }
        public string CheckCodeAfter { get; set; }
        public string RelateCondition { get; set; }
        public Nullable<bool> ShouldReturnToParent { get; set; }
        public string SourceTableName { get; set; }
        public string CodeColumnName { get; set; }
        public string TextColumnName { get; set; }
        public Nullable<bool> Sort { get; set; }
        public Nullable<bool> IsExclusiveTable { get; set; }
        public string DataTableName { get; set; }
        public Nullable<int> SourceFieldId { get; set; }
        public int FieldTypeId { get; set; }
        public Nullable<int> RelatedViewId { get; set; }
        public string List { get; set; }
        public Nullable<int> BackgroundColor { get; set; }
        public int ViewId { get; set; }
        public Nullable<int> PageId { get; set; }
    
        public virtual metaFieldType metaFieldType { get; set; }
        public virtual metaPage metaPage { get; set; }
        public virtual metaView metaView { get; set; }
        public virtual metaView metaView1 { get; set; }
    }
}
