//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class metaGridColumn
    {
        public int GridColumnId { get; set; }
        public string Name { get; set; }
        public Nullable<short> Size { get; set; }
        public short Position { get; set; }
        public string Text { get; set; }
        public bool ShouldRepeatLast { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<bool> IsReadOnly { get; set; }
        public string Pattern { get; set; }
        public string Upper { get; set; }
        public string Lower { get; set; }
        public int Width { get; set; }
        public string SourceTableName { get; set; }
        public string CodeColumnName { get; set; }
        public string TextColumnName { get; set; }
        public Nullable<bool> Sort { get; set; }
        public Nullable<bool> IsExclusiveTable { get; set; }
        public string DataTableName { get; set; }
        public int FieldId { get; set; }
        public int FieldTypeId { get; set; }
        public Nullable<bool> IsUniqueField { get; set; }
    }
}
