//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class metaBackground
    {
        public int BackgroundId { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string ImageLayout { get; set; }
        public Nullable<int> Color { get; set; }
    }
}
