//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class metaPage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public metaPage()
        {
            this.metaFields = new HashSet<metaField>();
        }
    
        public int PageId { get; set; }
        public string Name { get; set; }
        public short Position { get; set; }
        public string CheckCodeBefore { get; set; }
        public string CheckCodeAfter { get; set; }
        public int BackgroundId { get; set; }
        public int ViewId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<metaField> metaFields { get; set; }
        public virtual metaView metaView { get; set; }
    }
}
