//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class metaPattern
    {
        public int PatternId { get; set; }
        public string Expression { get; set; }
        public string Mask { get; set; }
        public string FormattedExpression { get; set; }
        public int DataTypeId { get; set; }
    
        public virtual metaDataType metaDataType { get; set; }
    }
}
