//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResponse
    {
        public System.Guid ResponseId { get; set; }
        public System.Guid SurveyId { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public int StatusId { get; set; }
        public string ResponseXML { get; set; }
        public string ResponsePasscode { get; set; }
        public Nullable<long> ResponseXMLSize { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsDraftMode { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<System.Guid> ParentRecordId { get; set; }
        public Nullable<System.Guid> RelateParentId { get; set; }
        public Nullable<int> RecordSourceId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
    }
}
