//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Data.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPIInfo7Entities : DbContext
    {
        public EPIInfo7Entities()
            : base("name=EPIInfo7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<metaBackground> metaBackgrounds { get; set; }
        public virtual DbSet<metaDataType> metaDataTypes { get; set; }
        public virtual DbSet<metaField> metaFields { get; set; }
        public virtual DbSet<metaFieldType> metaFieldTypes { get; set; }
        public virtual DbSet<metaGridColumn> metaGridColumns { get; set; }
        public virtual DbSet<metaImage> metaImages { get; set; }
        public virtual DbSet<metaLayerRenderType> metaLayerRenderTypes { get; set; }
        public virtual DbSet<metaLayer> metaLayers { get; set; }
        public virtual DbSet<metaLink> metaLinks { get; set; }
        public virtual DbSet<metaMapLayer> metaMapLayers { get; set; }
        public virtual DbSet<metaMapPoint> metaMapPoints { get; set; }
        public virtual DbSet<metaMap> metaMaps { get; set; }
        public virtual DbSet<metaPage> metaPages { get; set; }
        public virtual DbSet<metaPattern> metaPatterns { get; set; }
        public virtual DbSet<metaProgram> metaPrograms { get; set; }
        public virtual DbSet<metaView> metaViews { get; set; }
        public virtual DbSet<metaDbInfo> metaDbInfoes { get; set; }
    }
}
