//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class metaFieldType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public metaFieldType()
        {
            this.metaFields = new HashSet<metaField>();
        }
    
        public int FieldTypeId { get; set; }
        public string Name { get; set; }
        public bool HasFont { get; set; }
        public bool HasRepeatLast { get; set; }
        public bool HasRequired { get; set; }
        public bool HasReadOnly { get; set; }
        public bool HasRetainImageSize { get; set; }
        public bool IsDropDown { get; set; }
        public bool IsGridColumn { get; set; }
        public bool IsSystem { get; set; }
        public int DefaultPatternId { get; set; }
        public int DataTypeId { get; set; }
    
        public virtual metaDataType metaDataType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<metaField> metaFields { get; set; }
    }
}
